baseURL = "https://galleon8.github.io/"
locale = "en-US"
title = "g8 blog"
theme = "terminal"
pagination.pagerSize = 5
enableRobotsTXT = true

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  subtitle = "Notes, essays, and project updates."
  showMenuItems = 4
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = false
  showLastUpdated = false
  readingTime = true
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

[params.logo]
  logoText = "galleon8"
  logoHomeLink = "/posts/"

[languages]
  [languages.en]
    label = "English"

    [languages.en.params]
      subtitle = "Notes, essays, and project updates."
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "galleon8"
        logoHomeLink = "/posts/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 30

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn↗"
    url = "https://www.linkedin.com/in/gene-danilov/"
    weight = 40

    [menu.main.params]
      newTab = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'